openapi: 3.0.1
paths:
  /accounts/{accountId}:
    get:
      operationId: showAccount
      parameters:
      - name: accountId
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                type: string
  /catalog:
    get:
      operationId: showCatalog
      responses:
        default:
          description: default response
          content:
            text/plain:
              schema:
                type: string
  /{job-id}:
    get:
      operationId: get
      parameters:
      - name: wait
        in: query
        schema:
          type: integer
          format: int64
          default: -1
      - name: job-id
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            '*/*': {}
    post:
      operationId: readAndRemove
      parameters:
      - name: wait
        in: query
        schema:
          type: integer
          format: int64
          default: -1
      - name: job-id
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            '*/*': {}
    delete:
      operationId: remove
      parameters:
      - name: job-id
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            '*/*': {}
